### PR TITLE
Add support for tsconfig `paths`. (fixes #150)

### LINKED ISSUE #150: Support for tsconfig `paths`
In my `tsconfig.json` I use the `paths` option:

```json
"compilerOptions": {
  [...]

  "paths": {
    "@*": ["./src/*"]
  },
}
```

Which allows me to import files as such:

```ts
import validateToken from "@auth/jwt"; // => <root>/src/auth/jwt.ts
```

However ncc's module resolution is incompatible with this feature, giving the following error:

```bash
ncc: Module directory "<dir>" attempted to require "@auth/jwt" but could not be resolved, assuming external.
``` 

Something like `tsconfig-paths-webpack-plugin` could be used to support this configuration.

*I could submit a PR for this if there are no objections.*

### PR DESCRIPTION
**Pull request by odensc**
This PR adds support for the `paths` option in tsconfig, using `tsconfig-paths-webpack-plugin`.

### CODE REVIEW

**Comment by rauchg** [comment]
@odensc I really cannot accept this without tests. Any chance you can add a few? Thank you!

**Comment by rauchg** [comment]
I believe we already have a typescript test in there! `request-ts.ts`, which tests bundling `request`

**Comment by odensc** [comment]
@rauchg I couldn't actually find that file in the repo - until 804ee91e1e00a1ba8615bbc6bb33b4e0c6caf79c there were no `.ts` files at all. I've added a couple tests though, let me know how that looks. :)

**Comment by rauchg** [comment]
My bad @odensc – I'd totally forgotten to push my `.ts` integration test:
https://github.com/zeit/ncc/commit/d4d0eadfa1298a661e3447110e2f48f64d3af91d

Would you mind adding another one for paths?

**Pull request merged**
