### PR TITLE
Update jugglingdb to 2.0.1

### PR DESCRIPTION
**Pull request by styfle**
This fixes a potential security vulnerability.

Related to https://github.com/1602/jugglingdb/pull/460

Fixes: #303

### CODE REVIEW

**Comment by styfle** [comment]
> ✕ should execute "ncc run jugglingdb.js" (818ms)

@guybedford I broke it 😞 

I'm not sure what the original use case was here.

Should we continue testing the old version and add a new test for the new version? 🤔

**Comment by rauchg** [comment]
Tests are failing

**Comment by guybedford** [comment]
I've reported on this case here - https://github.com/zeit/ncc/issues/303.

**Comment by guybedford** [comment]
I've just pushed an update to the asset relocator loader here, which goes with the approach (1) described in #303. This does have some minor perf cost (roughly 5%), but allows this case to be built and handled properly, ensuring we only build one copy of jugglingdb.

**Pull request merged**
