### PR TITLE
Update to webpack-asset-relocator-loader@0.7.2

### PR DESCRIPTION
**Pull request by guybedford**

### CODE REVIEW

**Comment by guybedford** [comment]
@styfle would be good to get the next release made with this merge.

**Comment by styfle** [comment]
@guybedford Do you still have permission to release or do you need me to do it?

**Comment by guybedford** [comment]
Ah I see I do have permission, sure I can do it.

**Comment by guybedford** [comment]
@styfle actually I don't seem to have GitHub permission to push the release commit to master.

**Comment by styfle** [comment]
@guybedford You should have permission now

**Comment by guybedford** [comment]
@styfle I'm still getting:

```
it push origin 0.22.2remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: 2 of 2 required status checks are expected. At least 1 approving review is required by reviewers with write access.
To github.com:zeit/ncc
 ! [remote rejected] master -> master (protected branch hook declined)
```

**Comment by styfle** [comment]
@guybedford I published https://github.com/zeit/ncc/releases/tag/0.22.2

**Pull request merged**
