### PR TITLE
Fix top level return

### PR DESCRIPTION
**Pull request by rauchg**
It seems @sokra doesn't expose any clean hooks for extending the config, so for now we overload the method.

This makes the `path-platform` integration test pass.

### CODE REVIEW

**Comment by timneutkens** [comment]
I think we need a test for this 🤔

**Comment by TooTallNate** [comment]
@timneutkens The test is in https://github.com/zeit/ncc/commit/0a4c78989b548e524140f9f9f2eb4a11a243e0bc

**Comment by vitalyster** [comment]
It is broken again since 0.8.0

**Comment by vitalyster** [comment]
@guybedford [Here it is](https://github.com/vitalyster/ncc-gh43)

**Comment by guybedford** [comment]
@vitalyster the problem there is that `return` is not supported in ES modules, and that won't work under `node --experimental-modules` either.

**Comment by vitalyster** [comment]
But it works under Babel and works in ncc 0.7

**Comment by guybedford** [comment]
That it ever works is the incorrect behaviour.

**Comment by vitalyster** [comment]
Awesome! Work again in 0.14! Please don't break :)

**Pull request merged**
